#!/usr/bin/env node

/**
 * lib/freemotion-browser/build.mjs — write the two page-side helper files
 * from the code that already lives in lib/.
 *
 * The browser helpers in this folder load `inventory-global.js` and
 * `validate-global.js` into the page by FILE PATH, so the agent never has to
 * paste a 46 KB script into its prompt. Those two files are not hand-written:
 * they are `FORM_INVENTORY_SCRIPT` (lib/freemotion-inventory.mjs) and
 * `DOM_VALIDATION_SCRIPT` (lib/freemotion-validate.mjs), each assigned to a
 * window global. Before this file existed they were copied by hand into tmp/,
 * which meant a fix made in lib/ never reached the overnight run.
 *
 * Run it after changing either lib module. `--check` exits 1 when the files on
 * disk no longer match lib/, and tests/freemotion-browser.test.mjs runs it, so
 * a forgotten rebuild fails the test suite instead of silently shipping stale
 * page code.
 *
 * Usage:
 *   node lib/freemotion-browser/build.mjs            # write both files
 *   node lib/freemotion-browser/build.mjs --check    # exit 1 if out of date
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import { isMainModule } from '../is-main-module.mjs';
import { FORM_INVENTORY_SCRIPT } from '../freemotion-inventory.mjs';
import { DOM_VALIDATION_SCRIPT } from '../freemotion-validate.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

const HEADER = '// GENERATED by lib/freemotion-browser/build.mjs. Do not edit: change lib/ and rebuild.\n';

/** Each generated file, with the window global the helpers look it up by. */
export const GENERATED = [
  { file: 'inventory-global.js', global: '__fmInventory', script: FORM_INVENTORY_SCRIPT },
  { file: 'validate-global.js', global: '__fmValidate', script: DOM_VALIDATION_SCRIPT },
];

/**
 * The exact text a generated file must hold.
 *
 * @param {{global: string, script: string}} entry
 * @returns {string}
 */
export function render(entry) {
  return `${HEADER}window.${entry.global} = ${entry.script};\n`;
}

/**
 * Names of generated files that are missing or differ from lib/.
 *
 * @param {string} [dir]
 * @returns {string[]}
 */
export function staleFiles(dir = HERE) {
  return GENERATED
    .filter((entry) => {
      const path = join(dir, entry.file);
      if (!existsSync(path)) return true;
      return readFileSync(path, 'utf-8').replace(/\r\n/g, '\n') !== render(entry);
    })
    .map((entry) => entry.file);
}

function main(argv) {
  if (argv.includes('--check')) {
    const stale = staleFiles();
    if (stale.length === 0) {
      console.log('freemotion-browser: generated files match lib/');
      return 0;
    }
    console.error(`freemotion-browser: out of date: ${stale.join(', ')}. Run: node lib/freemotion-browser/build.mjs`);
    return 1;
  }
  for (const entry of GENERATED) {
    writeFileSync(join(HERE, entry.file), render(entry));
    console.log(`wrote lib/freemotion-browser/${entry.file}`);
  }
  return 0;
}

if (isMainModule(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
