// GENERATED by lib/freemotion-browser/build.mjs. Do not edit: change lib/ and rebuild.
window.__fmValidate = () => {
  // An ARIA combobox that accepts several values keeps its committed values as
  // CHIPS in an adjacent listbox and leaves its own input empty. Reading only
  // el.value therefore reports a field the user has answered as unanswered —
  // on Thales/Workday (#594) that was every multiselect on the step, including
  // a required one, so a correctly-filled form could never advance.
  //
  // Generic, not vendor-specific: role="listbox" holding li chips is the ARIA
  // pattern. The open dropdown is excluded by skipping role="option" items, and
  // the walk stops at the control's OWN container (the nearest ancestor holding
  // exactly one control), so a field can never inherit its neighbour's chips.
  const selectedChips = (el) => {
    let node = el;
    for (let i = 0; i < 3 && node.parentElement; i++) {
      node = node.parentElement;
      const owned = node.querySelectorAll('input:not([type=hidden]), select, textarea');
      if (owned.length > 1) break;
      const chips = [...node.querySelectorAll('ul[role="listbox"] li, ul[aria-label*="selected" i] li')]
        .filter((li) => li.getAttribute('role') !== 'option')
        .map((li) => (li.textContent || '').trim())
        .filter(Boolean);
      if (chips.length) return chips.join(', ');
    }
    return '';
  };
  const controls = [...document.querySelectorAll(
    'input:not([type=hidden]), select, textarea, [contenteditable="true"],' +
    ' [role="checkbox"], [role="radio"], [role="combobox"], [role="listbox"]'
  )];
  const fields = controls.map((el) => ({
    name: el.getAttribute('name') || el.getAttribute('aria-label')
          || el.getAttribute('data-automation-id') || el.id || '',
    tag: el.tagName.toLowerCase(),
    type: el.getAttribute('type') || el.getAttribute('role') || '',
    value: ('value' in el ? String(el.value ?? '') : (el.textContent || '').trim())
      || selectedChips(el),
    // Only where it MEANS something. Every <input> carries a .checked
    // property regardless of type, so testing mere presence stamped
    // checked:false onto every text box — and a consumer that reads it
    // before the value then sees every filled field as empty. Found live
    // on Thales/Workday (#594), where it failed a fully-filled step.
    checked: /^(checkbox|radio|switch)$/i.test(el.getAttribute('type') || el.getAttribute('role') || '')
      ? Boolean(el.checked) : undefined,
    required: el.hasAttribute('required') || el.getAttribute('aria-required') === 'true',
    invalid: el.getAttribute('aria-invalid') === 'true',
    disabled: Boolean(el.disabled) || el.getAttribute('aria-disabled') === 'true',
    visible: !!(el.offsetParent || el.getClientRects().length),
  }));
  const alerts = [...document.querySelectorAll('[role="alert"]')]
    .filter((el) => el.offsetParent || el.getClientRects().length)
    .map((el) => (el.textContent || '').trim())
    .filter(Boolean);
  return { fields, visibleAlerts: alerts, url: location.href, title: document.title };
};
